name: gpii-sites
recipe: drupal7
config:
  php: '7.3'
  webroot: web
  xdebug: true
  conf: 
    # Tell Lando to use additional PHP settings.
    # The location of this file is arbitrary. 
    # We placed it inside .vscode/ folder simply because we find it convenient.
    # php: .vscode/php.ini
services:
  database2:
    type: mysql:5.7
    portforward: true
    hostnames:
      -database2
      -database2.gpiisites.internal
    creds:
      user: drupal7
      password: drupal7
      database: ul
    config:
      confd: lando_config/mysql
  solr:
    type: solr:6.6
    portforward: 9999
    config:
      dir: solr-config
proxy:
  appserver: 
    - gpii.lndo.site
    - ul.gpii.lndo.site
    - ds.gpii.lndo.site
    - dev.gpii.net
    - dev.ds.gpii.net
    - dev.ul.gpii.net