<?php

/**
 * @file
 * Display Suite Bootstrap Two Col 2 22 configuration.
 */

function ds_bootstrap_2_22() {
  return array(
    'label' => t('Bootstrap Two Col 2-22'),
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right')
    ),
    // Uncomment if you want to include a CSS file for this layout (bootstrap_2_22.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (bootstrap_2_22.png)
    'image' => TRUE,
  );
}
