<?php

/**
 * @file
 * Display Suite Bootstrap Two Col 2 22 configuration.
 */

function ds_bootstrap_8_16() {
  return array(
    'label' => t('Bootstrap Two Col 8-16'),
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right')
    ),
    // Uncomment if you want to include a CSS file for this layout (bootstrap_8_16.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (bootstrap_8_16.png)
    'image' => TRUE,
  );
}
