<?php

/**
 * @file
 * Display Suite Bootstrap One Col 24 configuration.
 */

function ds_bootstrap_one_col_24() {
  return array(
    'label' => t('Bootstrap One Col 24'),
    'regions' => array(
      'main' => t('Main'),
    ),
    // Uncomment if you want to include a CSS file for this layout (bootstrap_one_col_24.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (bootstrap_one_col_24.png)
    // 'image' => TRUE,
  );
}
